name: Generate Snake Animation

on:
  schedule:
    # run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Generate and Publish Snake GIF
    runs-on: ubuntu-latest

    steps:
      # 1) Precisamos fazer checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Gerar a animação Snake
      - name: Generate snake animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ingridycandido
          # gera o gif
          gif_out_path: dist/github-contribution-grid-snake.gif

      # 3) Publicar no branch `output`
      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
